### ISSUE TITLE
фикс выбора участника

### ISSUE THREAD

**Issue by Ane1y** [OldKrab/winner_of_day#1]
здравствуйте, дорогая команда разработки бота "Победитель Дня"!

повысьте, пожалуйста, вероятность выбора участника, если он слишком редко выпадает победителем дня. 

В группе, где используется бот, есть челы которых выбрали уже раз 5, а есть кто-то кого бот выбрал только один раз, и ему очень грустно:(

**Comment by OldKrab** [comment]
Здравствуйте @Ane1y! По многочисленым просьбам мы реализовали данное улучшение. Спасибо за интерес к нашему продукту!
